<a href="https://colab.research.google.com/github/Dipanshu145/Demo/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('hello')

hello


this is demo

In [2]:
import numpy as np

In [3]:
data = [1,2,3,4,5,6,7,8,9]
arr = np.array(data)
print(type(data))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(type(arr1))
print(arr1.ndim)

<class 'numpy.ndarray'>
2


In [6]:
arr1.shape

(3, 3)

In [7]:
arr1.size


9

In [8]:
new_arr = np.array([1,2,3,4,5])

In [9]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

type casting
stype (dtype)


In [11]:
np.zeros((10),dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((10),dtype='float')


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((10),dtype='str')

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [16]:
n = np.arange(0,5)
n


array([0, 1, 2, 3, 4])

In [17]:
m = np.arange(10,5, -1)
m


array([10,  9,  8,  7,  6])

In [18]:
n = np.arange(1,10)
n


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [21]:
ones = np.ones((3,4))
ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
ones = np.ones((3,4),dtype="int")
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#1 3d array tensor and to creater 3d array


In [25]:
arr3d = np.array([
    [
        [1,2],
        [3,4],
    ],
    [
        [5,6],
        [8,8],
    ]

])
arr3d.ndim

3

In [30]:
new_arr = np.full((3,3),5)
new_arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [33]:
new_arr = np.full((3,2),5)
new_arr

array([[5, 5],
       [5, 5],
       [5, 5]])

In [34]:
import random

In [35]:
n = random.randint(1,100)
n

47

In [37]:
n = random.random()
n


0.17933624378033897

In [47]:
n2 = random.choices([1,2,3,4,5,6])
n2

[2]

In [49]:
n = np.linspace(1,18,5)
n

array([ 1.  ,  5.25,  9.5 , 13.75, 18.  ])

In [50]:
n = np.linspace(1,5,5)
n

array([1., 2., 3., 4., 5.])

In [52]:
n = np.linspace(1,100,1)
n

array([1.])

linespace
  
 or logspace
 log

In [54]:
n =np.logspace(1,10,10)
n

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [56]:
n =np.linspace(1,10,10)
n

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
data = np.array([1,2,3,4,5,6,7,8,9])
arr = np.array(data)
arr{0}

SyntaxError: invalid syntax (ipython-input-3294781252.py, line 3)

# fancy indexing

In [60]:
data = np.array([1,2,3,4,5,6,7,8,9])
arr = np.array(data)
mask = [1,5,0]
arr[mask]
arr[[2,4,3,1]]

array([3, 5, 4, 2])

#normal indexing on 2d array

In [73]:
aar2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
aar2d[1,2]

np.int64(6)

In [68]:
# number of elements in each column should be shame in numoy
# array_name = [row, column]
aar2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
aar2d[1:3,:] # using sliing (1:3 for 1 to 3 row ) and ( : ) for all

array([[4, 5, 6],
       [7, 8, 9]])

In [69]:
aar2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
aar2d[:,1:3] # using sliing (1:3 for 1 to 3 row ) and ( : ) for all

array([[2, 3],
       [5, 6],
       [8, 9]])

In [72]:
aar2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
aar2d[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [80]:
# (my_list[::2]) [0, 2, 4, 6, 8]
# aar2d[start:stop:step]
aar2d[::2, ::2]

array([[1, 3],
       [7, 9]])

In [81]:
data = [1,2]*2 # here it is dobule printed
print(data)

[1, 2, 1, 2]


In [82]:
data = np.array([1,2])*2 # in these it get multiplied by 2
print(data)

[2 4]


In [84]:
import time