<a href="https://colab.research.google.com/github/Dipanshu145/Demo/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('hello')

hello


this is demo

In [2]:
import numpy as np

In [3]:
data = [1,2,3,4,5,6,7,8,9]
arr = np.array(data)
print(type(data))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(type(arr1))
print(arr1.ndim)

<class 'numpy.ndarray'>
2


In [6]:
arr1.shape

(3, 3)

In [7]:
arr1.size


9

In [8]:
new_arr = np.array([1,2,3,4,5])

In [9]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

type casting
stype (dtype)


In [11]:
np.zeros((10),dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((10),dtype='float')


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((10),dtype='str')

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [16]:
n = np.arange(0,5)
n


array([0, 1, 2, 3, 4])

In [17]:
m = np.arange(10,5, -1)
m


array([10,  9,  8,  7,  6])

In [18]:
n = np.arange(1,10)
n


array([1, 2, 3, 4, 5, 6, 7, 8, 9])